/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prueba;

import java.awt.Color;

/**
 *
 * @author guefr
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario_input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contrasena_input = new javax.swing.JTextField();
        Iniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forget_password = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(237, 233, 227));

        underground.setBackground(new java.awt.Color(237, 233, 227));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("User Name");

        usuario_input.setBackground(new java.awt.Color(157, 159, 137));
        usuario_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuario_inputMouseClicked(evt);
            }
        });
        usuario_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_inputActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");

        contrasena_input.setBackground(new java.awt.Color(157, 159, 137));

        Iniciar.setBackground(new java.awt.Color(157, 159, 137));
        Iniciar.setText("Sign Up");
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMouseClicked(evt);
            }
        });
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 166, 166));
        jLabel3.setText("EcoDelivery");

        jLabel4.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("\"Entrega Verde Futuro Brillante\"");

        forget_password.setBackground(new java.awt.Color(237, 233, 227));
        forget_password.setForeground(new java.awt.Color(0, 0, 0));
        forget_password.setText("Forget Password?");
        forget_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_passwordMouseClicked(evt);
            }
        });
        forget_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout undergroundLayout = new javax.swing.GroupLayout(underground);
        underground.setLayout(undergroundLayout);
        undergroundLayout.setHorizontalGroup(
            undergroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undergroundLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(undergroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuario_input, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(undergroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(undergroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(363, Short.MAX_VALUE))
                    .addComponent(contrasena_input, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(undergroundLayout.createSequentialGroup()
                .addGroup(undergroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(undergroundLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel3))
                    .addGroup(undergroundLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, undergroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forget_password)
                .addGap(308, 308, 308))
        );
        undergroundLayout.setVerticalGroup(
            undergroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undergroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forget_password)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(underground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(underground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseClicked
         // TODO add your handling code here:
        var usuarios=peticiones1.obtenerUsuarios();
        System.out.println("Entre al botón");
        String usuario=usuario_input.getText();
        System.out.println(usuario);
        jLabel1.setText("Hola cambie gracias al boton");
        contrasena_input.setBackground(Color.red);
        System.out.println("Entre al botón");
        String contrasena=contrasena_input.getText();
        System.out.println(contrasena);
        
        LoginSistema login = new LoginSistema();

        // Prueba de verificación

        if (login.verificarAcceso(usuario, contrasena)) {
            System.out.println("✅ Acceso concedido.");
            principal MiPrincipal = new principal();
            MiPrincipal.setVisible(true);
            dispose();
        } else {
            System.out.println("❌ Usuario o contraseña incorrectos.");
        }
        
        
              
    }//GEN-LAST:event_IniciarMouseClicked

    private void usuario_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_inputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuario_inputActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarActionPerformed

    private void forget_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forget_passwordActionPerformed

    private void usuario_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_inputMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuario_inputMouseClicked

    private void forget_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_passwordMouseClicked
        // TODO add your handling code here:
        siginup MiPrincipal = new siginup();
       MiPrincipal.setVisible(true);
    }//GEN-LAST:event_forget_passwordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField contrasena_input;
    private javax.swing.JButton forget_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel underground;
    private javax.swing.JTextField usuario_input;
    // End of variables declaration//GEN-END:variables
}
